### ISSUE TITLE
is it possible to run radio downloader on mac or android

### ISSUE THREAD

**Issue by mandywr** [ribbons/RadioDownloader#200]
I am having to abandon my old  windows xp  pc and am thinking of moving to mac.

**Comment by ribbons** [comment]
I believe that it is possible to run Radio Downloader on a Mac - issue #55 covers this request and contains some details from someone who was able to get it running under Wine with macports.

Unfortunately there isn't an android version of Radio Downloader and there are no current plans to write one.
