### ISSUE TITLE
Option to edit the feed URL

### ISSUE THREAD

**Issue by SDRoffey** [ribbons/RadioDownloader#201]
Hi,

Would it be possible to add an option to view and/or edit the URL of the podcast feed?

I've had a couple of instances where a feed has stopped working, but when I look at the website, the programs are there. I just want a way of checking that Radio Downloader has the correct URL, or whether there is another problem stopping the downloads.

Many thanks,

Simon

**Comment by ribbons** [comment]
Should be possible to at least enable viewing it - will have a think and see what I can do.

**Comment by SDRoffey** [comment]
Thanks, being able to view the URL would be useful.

**Comment by ribbons** [comment]
Have added a 'More Info' button to the toolbar which shows this dialog for podcasts:

![Feed URL](https://cloud.githubusercontent.com/assets/961548/13906862/14800908-eed9-11e5-9398-6f6501569c14.png)

Will have to publish a build soon - need to get a new code signing certificate first though...

**Comment by ribbons** [comment]
Actually, now I've got AppVeyor set up properly, you should be able to give this feature a whirl using the build from here: https://ci.appveyor.com/project/ribbons/radiodownloader/build/18/job/9k80aqxnunp72fwu/artifacts

**Comment by SDRoffey** [comment]
Hi Matt,

Just downloaded and installed this update and it works a treat.

Thanks,

Simon

**Comment by ribbons** [comment]
Great - glad to hear it!
