### ISSUE TITLE
Add variable Episode ID for use in the File Name formats

### ISSUE THREAD

**Issue by nbl1268** [ribbons/RadioDownloader#220]
Add EpisodeId (%epid%) as variable that can be included by the user in the file name formats for downloads
example
![image](https://user-images.githubusercontent.com/1731666/33548379-1838189e-d93b-11e7-8a25-51c5cfff8d47.png)

suggested change in download.cs
1/ insert at line 483 (before existing code for %hour%)
     `fileName = fileName.Replace("%epid%", epInfo.Epid.ToString());`

**Comment by ribbons** [comment]
I think my main question would be why..?

**Comment by nbl1268** [comment]
Fair question.. the media player in my vehicle has accepts USB drive and has limited audio track play order options.  'Play by Filename' in alphabetical ascending is what it copes with. 
So for me to be able to add the ID to the file name (option instead of year month date etc) this will put the files in the right order for this old player and make it easier for me to identify the next batch to copy over to the USB plugged in to the vehicle media player.

Anyhow, rather minor enhancement to add to the list.
Bigger question i have is which if the other issues on the list can i help out with?

**Comment by ribbons** [comment]
Episode id isn't guaranteed to be in any particular order and won't always be in either date or download order.  The correct way of getting alphabetical ordering of filenames is using a %year%%month%%day% %hour%%minute% or similar prefix for the filename template.

For identifying the next batch of files to copy over, using the 'Run command after download' function can solve this problem by setting up a copy of newly downloaded episodes to a different folder on your computer, ready to move to your USB device.

Re: other issues - take your pick :smile: - could be helpful to comment on an existing issue first to give me a heads up first though.
