### ISSUE TITLE
Certain subscribed podcast feeds have started to fail

### ISSUE THREAD

**Issue by jopijedd** [ribbons/RadioDownloader#224]
Hello,

I've had a problem for the past couple of weeks where previously successful podcast feeds have started failing. I have clicked "Report Error", but this doesn't appear to generate a report number. The error message is the "Unknown Error".

I have not knowingly done anything to cause the issue, but since it started happening, i have tidied up the downloads tab and run Clean Up, run the corrupt database utility and looked for anything obviously wrong using a SQL viewer. Nothing seems immediately apparent, although the database (currently running > 1Gb) is huge, presumably from all the images it is holding on to. The database current stretches back over three PCs (although not changed recently) and in to the days of the Beeb feeds.

![rdld](https://user-images.githubusercontent.com/39128103/39821814-f26b4cae-53a0-11e8-988c-b4b58098d545.png)

Current status is: 
Confirmed Working Feeds:
Radio X \ Danny Wallace	http://www.blogtalkradio.com/dax-global-radiox-dw/podcast
Radio X \ Chris Moyles	http://ws.geronimo.thisisglobal.com/api/RssFeed/GetPodcasts?StationId=27f88187-4880-4e70-be90-1a7dad1beb5e&amp;ShowId=999e3658-ae1a-400b-9697-5bc35d5aa411
Radio X \ Saturdays	http://ws.geronimo.thisisglobal.com/api/RssFeed/GetPodcasts?StationId=27f88187-4880-4e70-be90-1a7dad1beb5e&amp;ShowId=90e4fca4-402d-495c-8b19-566ac2dfc617
Radio X \ Johnny Vaughan	http://ws.geronimo.thisisglobal.com/api/RssFeed/GetPodcasts?StationId=27f88187-4880-4e70-be90-1a7dad1beb5e&amp;ShowId=effae27f-95f6-4796-967e-2ea7669a2035
Pappy's Flatshare Slamdown	http://feeds.feedburner.com/PappysFlatshareSlamdown

Confirmed Failed Feeds:
Iain Lee's Rabbit Hole	http://rss.acast.com/therabbithole
Iain Lee Late Night	http://talkradio.co.uk/itunes/talkradio-radio/the-late-night-alternative-with-iain-lee/podcast.xml
The The One Show Show	https://rss.acast.com/thetheoneshowshow

**Comment by jopijedd** [comment]
Sorry for repeating a previous error. I found the solution in the closed issues.

**Comment by ribbons** [comment]
No need to apologise & sorry the error reporting isn't working properly at the moment.  Am I right in thinking that you were hitting the same issue as #223?

**Comment by jopijedd** [comment]
Yes. I downloaded the build suggested in that post and it solved the problem. I briefly scanned through the closed issues before i started, but hadn't twigged it was a connection issue as i had convinced myself that something had gone awry in the database. Thank you for your continued work on this software, it is by far the most pleasant podcast handler i've been in contact with.

**Comment by ribbons** [comment]
Ah, cool. Sounds like I should make a release so it doesn't affect too many more users.
