### ISSUE TITLE
Give a useful error message to Windows users without the .NET framework TLS update installed

### ISSUE THREAD

**Issue by BarnetHill** [ribbons/RadioDownloader#229]
I am running windows 7 pro 64 bit.  The installation of RadioDownloader version V 0.32 failed with a message that RadioDownloader had encountered a problem.  I am not sure what to do now. I sent the automatic error report to you.

thanks

![RadioDownloader_01](https://user-images.githubusercontent.com/41081231/55029583-ccdfd300-4fe0-11e9-92c7-2f29e754a68d.JPG)

![RadioDownloader_02](https://user-images.githubusercontent.com/41081231/55029586-cfdac380-4fe0-11e9-838c-4e1801fee9b9.JPG)

**Comment by BarnetHill** [comment]
Actually I think it installed but I get the error when I try to run the program.

**Comment by ribbons** [comment]
Could you install the version from https://ci.appveyor.com/api/buildjobs/hml865oh30f8r67f/artifacts/installer%2FRadio_Downloader-win64.msi and let me know if that gives you a more descriptive error message?

**Comment by BarnetHill** [comment]
This was more helpful.   Where can I find the relevant Net Framework update?

![RadioDownloader_03](https://user-images.githubusercontent.com/41081231/55034086-0289b980-4feb-11e9-805b-837c3c26ed9a.JPG)

**Comment by BarnetHill** [comment]
I have 4.6.1 on this pc

**Comment by ribbons** [comment]
Are there any .NET Framework updates shown as available under Windows update?

**Comment by BarnetHill** [comment]
I found this

https://docs.microsoft.com/en-us/dotnet/framework/install/on-windows-7

So maybe I can do the update to 4.7.2.

**Comment by BarnetHill** [comment]
I installed version 4.7.2 but that didn't fix the problem. I then downloaded the two windows .net updates and all is working OK now.

Thanks

**Comment by ribbons** [comment]
Okay, great - glad the updates fixed the issue for you.  Marking this as resolved as the more useful error message was added in 90e0d9914035767073389da4570782645c487a15.
