### ISSUE TITLE
Can the episode name be made available as a parameter like %file%

### ISSUE THREAD

**Issue by ErikBrown2** [ribbons/RadioDownloader#230]
First thank you very much for this great program. I used to use Juice (iPodder) for years but after upgrading my Windows version I had to look for something else. RadioDownloader is downloading the programs reliably and comfortably.

After downloading programs from different podcasts, I would like to organise the downloaded files using a batch file. But the 'run command after download' option allows only the full program name (podcast name) to be used as %file% in the command. Would it be possible to also allow the program name %epname% to be used? This will allow the sorting of the programs in their own directory by calling batch file that does the moving of the file into a folder that has the program name in it. 

Or, otherwise, it will be great if each program can have it's own download sub folder where the subfolder is the program name. This will solve the issue of sorting the downloaded files too.

**Comment by ribbons** [comment]
Glad you're finding Radio Downloader useful.

Unless I'm misunderstanding, I think you could achieve something like the result you are after without a batch file by using the following filename format string: `%progname%\%epname% %day%-%month%-%year%`

There is a small amount more information about the filename format strings at https://nerdoftheherd.com/tools/radiodld/help/dialogs.options/ in case that is of use.

Let me know if that solves your issue or if I've got the wrong end of the stick.

**Comment by ribbons** [comment]
Closing issue as no response from reporter.
