### ISSUE TITLE
Unable to subscribe to 13 Minutes to the Moon

### ISSUE THREAD

**Issue by DonGrunbaum** [ribbons/RadioDownloader#231]
Trying to subscribe to URL https://podcasts.files.bbci.co.uk/w13xttx2.rss. RD eventually links to the podcast feed, but fails to identify episodes and also fails to subscribe. No error messages evident, just failure to respond.

**Comment by ribbons** [comment]
Many thanks for your bug report - unfortunately I can't reproduce the issue that you describe.  This is the list of episodes that Radio Downloader 0.32 shows for me if I enter the URL that you gave via Find Programme -> Podcast and press 'View':

![Episode List](https://user-images.githubusercontent.com/961548/58383674-83583800-7fd1-11e9-85d3-fdc7b1698e98.png)

Am I doing the same steps as you or have I misunderstood your report?

**Comment by DonGrunbaum** [comment]
Hello Matt

Thanks for the response.

After some time (15 minutes or so) it did eventually list the episodes and 
I've managed to download them, although RD didn't do it automatically. I guess 
it might have done if 
I's waited long enough.

Is there anything that might cause RD to take a long while to recognise the URL and then to find the episodes? e.g. a large database?

Best wishes

Don


----- Original Message -----

**Comment by ribbons** [comment]
Ah, okay - glad it listed them in the end.  From your description I'd hazard a guess that there was some kind of issue between you and their server.  Would be interesting to know what size your Radio Downloader database (store.db in the folder %appdata%\nerdoftheherd.com\Radio Downloader) is though.
