### ISSUE TITLE
feature request/Notifications: just like when the main rd window is closed, and you are enformed that rd will keep running to get your latest subscriptions, hows about a notification that enformes you when rd is in the process of downloading new epesodes?

### ISSUE THREAD

**Issue by mhussaincov93** [ribbons/RadioDownloader#249]
reasoning:
it would be nice to know when epesodes start downloading it would mean that you would not go checking every x amounts of minutes like I doo.
something like
your subscriptions have started downloading!
post note,
I like the Notifications you get when you close rd, concise and gets to the point.
Majid

**Comment by ribbons** [comment]
In theory this should be possible but I'm not completely sure of the use-case of receiving a notification when downloads have started - are you able to elaborate?

If you're interested in being notified when a download has completed successfully it should be possible to set something up via the 'Run command after download' function in the options.
